scriptsToRun = {...
    @caliber.test.stereo00,...
    @caliber.test.sphericalGantry00,...
    @caliber.test.tablet00,...
    @caliber.test.twoarm,...
    @caliber.test.facing00,...
    @caliber.test.nonoverlap00,...
    @caliber.test.ladybug00};
    
elapsedTimes = zeros(size(scriptsToRun));
for i = 1:numel(scriptsToRun)
    tStart = tic();
    scriptsToRun{i}();
    elapsedTimes(i) = toc(tStart);
end

for i = 1:numel(scriptsToRun)
    fprintf('%s: %fs\n', func2str(scriptsToRun{i}), elapsedTimes(i));
end
