infos = {...
    {'caliber_data/stereo_03/c_results.mat', 'caliber_data/stereo_03/m_results.mat'}; ...
    {'caliber_data/spherical_00/Calib_Results.mat'};...
    {'caliber_data/tablet02/cm_results.mat', 'caliber_data/tablet02/mm_results.mat', 'caliber_data/tablet02/t_results.mat'};...
    {'caliber_data/cal2arms/merged_results.mat'};...
    {'caliber_data/facing00/a_results.mat', 'caliber_data/facing00/d_results.mat'}; ...
    {'caliber_data/nonoverlap05/D_Results.mat', 'caliber_data/nonoverlap05/M_Results.mat', 'caliber_data/nonoverlap05/C_Results.mat', 'caliber_data/nonoverlap05/R_Results.mat'};...
    {'caliber_data/ladybug00/results1.mat', 'caliber_data/ladybug00/results2.mat', 'caliber_data/ladybug00/results3.mat', 'caliber_data/ladybug00/results4.mat', 'caliber_data/ladybug00/results5.mat'}};

rmsErrors = zeros(size(infos));
for i = 1:numel(infos)
    rmsErrors(i) = caliber.test.bouguetRMS(infos{i});
end
