infos = {...
    {'data/stereo_03/c_results.mat', 'data/stereo_03/m_results.mat'}; ...
    {'data/spherical_00/Calib_Results.mat'};...
    {'data/tablet02/cm_results.mat', 'data/tablet02/mm_results.mat', 'data/tablet02/t_results.mat'};...
    {'data/cal2arms/merged_results.mat'};...
    {'data/facing00/a_results.mat', 'data/facing00/d_results.mat'}; ...
    {'data/nonoverlap05/D_Results.mat', 'data/nonoverlap05/M_Results.mat', 'data/nonoverlap05/C_Results.mat', 'data/nonoverlap05/R_Results.mat'};...
    {'data/ladybug00/results1.mat', 'data/ladybug00/results2.mat', 'data/ladybug00/results3.mat', 'data/ladybug00/results4.mat', 'data/ladybug00/results5.mat'}};

rmsErrors = zeros(size(infos));
for i = 1:numel(infos)
    rmsErrors(i) = caliber.test.bouguetRMS(infos{i});
end
