function drawCameraFrustrum( M, K, resolution, scale )
%DRAWFRUSTRUM Summary of this function goes here
%   Detailed explanation goes here
    cameraBoxColor = [0.75 0.75 0];
    imageCorners = [0 resolution(1) resolution(1) 0;...
        0 0 resolution(2) resolution(2);...
        1 1 1 1];
    normPlaneCorners = scale * (K \ imageCorners);
    frustrumCorners = M * [normPlaneCorners; 1 1 1 1];
    cameraBase = M(1:3, 4);
    line([frustrumCorners(1, :) frustrumCorners(1, 1)],...
        [frustrumCorners(2, :) frustrumCorners(2, 1)],...
        [frustrumCorners(3, :) frustrumCorners(3, 1)],...
        'Color', cameraBoxColor);
    line([cameraBase(1) * ones(1, 4); frustrumCorners(1, :)],...
        [cameraBase(2) * ones(1, 4); frustrumCorners(2, :)],...
        [cameraBase(3) * ones(1, 4); frustrumCorners(3, :)],...
        'Color', cameraBoxColor);
end

